# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Lets start unit tests
  displayName: 'Unit tests with Python'

- script: |
    python -m pip install --upgrade pip
    pip install pytest pytest-azurepipelines
  displayName: 'Install dependencies'

- script: |
    python -m pytest tests1.py
  displayName: 'Tests 1'
  
- script: |
    python -m pytest tests2.py
  displayName: 'Tests 2'